### ISSUE TITLE
cyrillic caharacters are lost when saving 

### ISSUE THREAD

**Issue by Ryder17z** [moritz-h/satisfactory-3d-map#2]
Affects mostly signs. Probably applies to other things like train station names as well.

I'm not sure why it causes the signs to be reset to "shenanigans" with an iron ingot.

**Comment by moritz-h** [comment]
Fixed in f627949.

**Comment by moritz-h** [comment]
Writing of all non ascii strings was not working. There is a new release v0.5.1 including the fix.

**Comment by Ryder17z** [comment]
Very good.
